=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/message.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config (include*, protocol+)>
<!ATTLIST config namespace CDATA #REQUIRED>
<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>
<!ELEMENT protocol (toClient?,toServer?,returnMsg?)>
<!ATTLIST protocol 
    id CDATA #REQUIRED
    alias CDATA #IMPLIED
>
<!ELEMENT toClient (param*)>
<!ATTLIST toClient 
    desc CDATA #REQUIRED
    proto (true|false) "false"
    messageClass CDATA #IMPLIED
>
<!ELEMENT toServer (param*)>
<!ATTLIST toServer
    desc CDATA #REQUIRED
    proto (true|false) "false"
    class CDATA #REQUIRED
    messageClass CDATA #IMPLIED
    method CDATA #REQUIRED
>
<!ELEMENT returnMsg (msg+)>
<!ELEMENT param EMPTY>
<!ATTLIST param
    tag (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32) #REQUIRED
    fieldName CDATA #REQUIRED
    fieldType (string|int32|int64|bytes|bool) #REQUIRED
    repeated (true|false) "false"
    desc CDATA #IMPLIED
>
<!ELEMENT msg EMPTY>
<!ATTLIST msg 
    id CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/general.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="general">
    <protocol id="0x003A0102" alias="allGeneralInfo">
        <toClient desc="返回全部将宠信息" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserGeneralInfoProtobuf.UserGeneralInfoProto">
        </toClient>
        <toServer desc="获取全部将宠信息" class="com.kueem.webgame.game.action.game.GeneralAction" method="allGeneralInfo">
        </toServer>
    </protocol>
    <protocol id="0x003A0202" alias="zhaomu">
        <toClient desc="返回新招募的将宠信息" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserGeneralInfoProtobuf.UserGeneralInfoProto.UserGeneralProto">
        </toClient>
        <toServer desc="使用招兵令招募将宠" class="com.kueem.webgame.game.action.game.GeneralAction" method="zhaomu">
            <param fieldName="gid" tag="1" fieldType="int32" desc="将宠id"/>
        </toServer>
    </protocol>
    <protocol id="0x003A0302" alias="changeName">
        <toServer desc="改名字" class="com.kueem.webgame.game.action.game.GeneralAction" method="changeName">
            <param fieldName="ugid" tag="1" fieldType="int32" desc="用户将宠id"/>
            <param fieldName="name" tag="2" fieldType="string" desc="新名字"/>
        </toServer>
    </protocol>
    <protocol id="0x003A0502" alias="ronghe">
        <toServer desc="融合" class="com.kueem.webgame.game.action.game.GeneralAction" method="ronghe">
            <param fieldName="main" tag="1" fieldType="int32" desc="主宠id"/>
            <param fieldName="vice" tag="2" fieldType="int32" desc="副宠id"/>
        </toServer>
    </protocol>
    <protocol id="0x003A0602" alias="chuzhan">
        <toServer desc="出战" class="com.kueem.webgame.game.action.game.GeneralAction" method="chuzhan">
            <param fieldName="ugid" tag="1" fieldType="int32" desc="用户将宠id"/>
        </toServer>
    </protocol>
    <protocol id="0x003A0702" alias="zhaohui">
        <toServer desc="召回" class="com.kueem.webgame.game.action.game.GeneralAction" method="zhaohui">
        </toServer>
    </protocol>
    <protocol id="0x003A0802" alias="singleGeneralInfo">
        <toClient desc="返回单个将宠信息" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserGeneralInfoProtobuf.UserGeneralInfoProto.UserGeneralProto">
        </toClient>
        <toServer desc="获取单个将宠信息" class="com.kueem.webgame.game.action.game.GeneralAction" method="singleGeneralInfo">
            <param fieldName="ugid" tag="1" fieldType="int32" desc="用户将宠id"/>
        </toServer>
    </protocol>
    <protocol id="0x003A0902" alias="fangsheng">
        <toClient desc="放生结果">
            <param fieldName="ugid" tag="1" fieldType="int32" desc="删除的用户将宠id"/>
        </toClient>
        <toServer desc="放生" class="com.kueem.webgame.game.action.game.GeneralAction" method="fangsheng">
            <param fieldName="ugid" tag="1" fieldType="int32" desc="用户将宠id"/>
        </toServer>
    </protocol>
    <protocol id="0x003A0A02" alias="changeState">
        <toServer desc="切换出战将宠的战斗模式" class="com.kueem.webgame.game.action.game.GeneralAction" method="changeState">
            <param fieldName="state" tag="1" fieldType="int32" desc="状态"/>
        </toServer>
    </protocol>
    <protocol id="0x003A3A02">
        <toServer desc="将宠上阵" class="com.kueem.webgame.game.action.game.GeneralAction" method="sz">
            <param tag="1" fieldType="int32" fieldName="arrayId" desc="阵位id : 1-5,5代表主将位置"/>
            <param tag="2" fieldType="int32" fieldName="ugid" desc="上阵的将宠id"/>
        </toServer>
    </protocol>
    <protocol id="0x003A3B02">
        <toServer desc="将宠下阵" class="com.kueem.webgame.game.action.game.GeneralAction" method="xz">
            <param tag="1" fieldType="int32" fieldName="arrayId" desc="阵位id : 1-5,5代表主将位置"/>
        </toServer>
    </protocol>
    <protocol id="0x003A3F02" alias="anfu">
        <toServer desc="安抚(补充精力" class="com.kueem.webgame.game.action.game.GeneralAction" method="anfu">
            <param fieldName="ugid" tag="1" fieldType="int32"/>
            <param fieldName="index" tag="2" fieldType="int32"/>
        </toServer>
    </protocol>
    <protocol id="0x003A4502" alias="recentZhaomu">
        <toClient desc="同步最近玩家的招募信息">
            <param fieldName="uid" tag="1" fieldType="string" repeated="true"/>
            <param fieldName="uname" tag="2" fieldType="string" repeated="true"/>
            <param fieldName="gid" tag="3" fieldType="int32" repeated="true"/>
            <param fieldName="camp" tag="4" fieldType="int32" repeated="true"/>
        </toClient>
        <toServer desc="获取最近五条玩家的招募信息" class="com.kueem.webgame.game.action.game.GeneralAction" method="recentZhaomu">
        </toServer>
    </protocol>
    <protocol id="0x003A4602" alias="syncGeneralInfoToUser">
        <toClient desc="获取指定用户的指定宠物信息" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserGeneralInfoProtobuf.UserGeneralInfoProto.UserGeneralProto">
        </toClient>
        <toServer desc="获取指定用户的指定宠物信息" class="com.kueem.webgame.game.action.game.GeneralAction" method="syncUserGeneralToUser">
            <param fieldName="ownerId" tag="1" fieldType="string"/>
            <param fieldName="ugid" tag="2" fieldType="int32"/>
        </toServer>
    </protocol>
    <protocol id="0x003A4902" alias="baiji">
        <toClient desc="返回本次拜祭所获得的物品对应reward表的id">
            <param fieldName="reward_id" tag="1" fieldType="int32" repeated="true"/>
        </toClient>
        <toServer desc="拜祭" class="com.kueem.webgame.game.action.game.GeneralAction" method="baiji">
            <param fieldName="type" tag="1" fieldType="int32" desc="1:普通;2:高级;3:至尊"/>
        </toServer>
    </protocol>
    <protocol id="0x003A4A02" alias="open">
        <toServer desc="开格子" class="com.kueem.webgame.game.action.game.GeneralAction" method="open">
            <param fieldName="num" tag="1" fieldType="int32"/>
        </toServer>
    </protocol>
    <protocol id="0x003A5002" alias="tunshi">
        <toServer desc="吞噬" class="com.kueem.webgame.game.action.game.GeneralAction" method="tunshi">
            <param fieldName="type" tag="1" fieldType="int32" desc="1:募将令;2:宠物"/>
            <param fieldName="id" tag="2" fieldType="int32" repeated="true" desc="类型为1时表示在背包中位置;否则代表ugid"/>
            <param fieldName="ugid" tag="3" fieldType="int32" desc="宠物uid"/>
        </toServer>
    </protocol>
    <protocol id="0x003A5102" alias="upgradeWuxing">
        <toServer desc="提升悟性等级" class="com.kueem.webgame.game.action.game.GeneralAction" method="upgradeWuxing">
            <param fieldName="ugid" tag="1" fieldType="int32" desc="宠物uid"/>
            <param fieldName="type" tag="2" fieldType="int32" desc="0:一次提升;1:自动提升"/>
        </toServer>
    </protocol>
    <protocol id="0x003A5202" alias="equip">
        <toServer desc="装备神弩" class="com.kueem.webgame.game.action.game.GeneralAction" method="equip">
            <param fieldName="ugid" tag="1" fieldType="int32" desc="宠物uid"/>
            <param fieldName="index" tag="2" fieldType="int32" desc="神弩在背包中的位置"/>
        </toServer>
    </protocol>
    <protocol id="0x003A5302" alias="removeEquip">
        <toServer desc="卸下神弩" class="com.kueem.webgame.game.action.game.GeneralAction" method="removeEquip">
            <param fieldName="ugid" tag="1" fieldType="int32" desc="宠物uid"/>
            <param fieldName="position" tag="2" fieldType="int32" desc="要卸下的位置"/>
        </toServer>
    </protocol>
</config>

=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/spa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="spa">
    <protocol id="0x00280102" alias="获取现有温泉场景信息">
        <toClient desc="返回用现有温泉场景信息">
            <param fieldName="mapId" tag="1" fieldType="int32" repeated="true" /><!--场景id,数组 -->
            <param fieldName="num" tag="2" fieldType="int32" repeated="true" /><!--当前场景人数,数组 -->
        </toClient>
        <toServer desc="获取现有温泉场景信息" class="com.kueem.webgame.game.action.game.SpaAction" method="syncAllMaps">
        </toServer>
    </protocol>
    <protocol id="0x00280202" alias="enter">
        <toServer desc="进入温泉" class="com.kueem.webgame.game.action.game.SpaAction" method="enter">
            <param fieldName="mapId" tag="1" fieldType="int32" /><!--场景id -->
        </toServer>
    </protocol>
    <protocol id="0x00280302" alias="hit">
        <toClient desc="返回结果">
            <param fieldName="num" tag="1" fieldType="bool" />
        </toClient>
        <toServer desc="砸晕" class="com.kueem.webgame.game.action.game.SpaAction" method="hit">
            <param fieldName="uid" tag="1" fieldType="string" /><!--目标人物id -->
        </toServer>
    </protocol>
    <protocol id="0x00280402" alias="massage">
        <toClient desc="返回结果">
            <param fieldName="num" tag="1" fieldType="bool" />
        </toClient>
        <toServer desc="按摩" class="com.kueem.webgame.game.action.game.SpaAction" method="massage">
            <param fieldName="uid" tag="1" fieldType="string" /><!--目标人物id -->
        </toServer>
    </protocol>
    <protocol id="0x00280502" alias="restAddtionTime">
        <toClient desc="返回今日剩余互动收益次数">
            <param fieldName="num" tag="1" fieldType="int32" />
        </toClient>
    </protocol>
    <protocol id="0x00280602" alias="singlePractice">
        <toClient desc="返回结果">
            <param fieldName="num" tag="1" fieldType="bool" />
        </toClient>
        <toServer desc="单修" class="com.kueem.webgame.game.action.game.SpaAction" method="singlePractice">
        </toServer>
    </protocol>
    <protocol id="0x00280702" alias="doublePractice">
        <toClient desc="返回结果">
            <param fieldName="num" tag="1" fieldType="bool" />
            <param fieldName="selfId" tag="2" fieldType="string" />
            <param fieldName="targetId" tag="3" fieldType="string" />
        </toClient>
        <toServer desc="双修" class="com.kueem.webgame.game.action.game.SpaAction" method="doublePractice">
            <param fieldName="uid" tag="1" fieldType="string" /><!--目标人物id -->
        </toServer>
    </protocol>
    <protocol id="0x00280802" alias="stopSinglePractice">
        <toClient desc="返回结果">
            <param tag="1" fieldType="bool" desc="" fieldName="result" />
        </toClient>
        <toServer desc="打断单修" class="com.kueem.webgame.game.action.game.SpaAction" method="stopSinglePractice">
        </toServer>
    </protocol>
    <protocol id="0x00280902" alias="stopDoublePractice">
        <toClient desc="返回结果">
            <param tag="1" fieldType="bool" desc="" fieldName="result" />
        </toClient>
        <toServer desc="打断双修" class="com.kueem.webgame.game.action.game.SpaAction" method="stopDoublePractice">
        </toServer>
    </protocol>
</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/chat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="chat">
	<!-- 聊天模块 -->

	<!-- 接收参数：1 频道类型（私人，所有人，队伍，频道等等） 2 目标用户（只有私聊有这个参数） 3 目标用户 -->

	<protocol id="0x00050102" alias="send">
		<!-- 返回参数：1 发送者用户名，2 频道类型，3 目标用户名称 4 消息正文 5 时间 6 性别 7 vip等级 8 阵营 9 发送者ID 
			10 职业 -->
		<toClient desc="聊天信息">
			<param fieldName="senderName" tag="1" fieldType="string" />
			<param fieldName="channelType" tag="2" fieldType="int32" />
			<param fieldName="receiverName" tag="3" fieldType="string" />
			<param fieldName="msg" tag="4" fieldType="string" />
			<param fieldName="time" tag="5" fieldType="int64" />
			<param fieldName="gender" tag="6" fieldType="string" />
			<param fieldName="vipLevel" tag="7" fieldType="int32" />
			<param fieldName="camp" tag="8" fieldType="int32" />
			<param fieldName="senderUid" tag="9" fieldType="string" />
			<param fieldName="job" tag="10" fieldType="int32" />
		</toClient>
		<toServer desc="聊天"
			class="com.kueem.webgame.game.action.game.ChatAction" method="send">
			<param fieldName="channelType" tag="1" fieldType="int32" />
			<param fieldName="targetName" tag="2" fieldType="string" />
			<param fieldName="message" tag="3" fieldType="string" />
		</toServer>
	</protocol>

	<!-- id 快照ID type 类型 relId 引用的IDS -->
	<protocol id="0x00050202" alias="notifySnapshot">
		<toClient desc="通知客户端生成快照">
			<param fieldName="snapshotId" tag="1" fieldType="string" />
			<param fieldName="type" tag="2" fieldType="int32" />
			<param fieldName="relId" tag="3" fieldType="int32" />
		</toClient>
	</protocol>

	<!-- id 快照ID snapshot快照 -->
	<protocol id="0x00050302" alias="addSnapshot">
		<toServer desc="客户端将快照信息传递到服务器端"
			class="com.kueem.webgame.game.action.game.ChatAction" method="addSnapshot">
			<param fieldName="snapshotId" tag="1" fieldType="string" />
			<param fieldName="snapshot" tag="2" fieldType="string" />
		</toServer>
	</protocol>

	<!-- id 快照ID -->
	<protocol id="0x00050402" alias="findSnapshot">
		<toServer desc="通知客户端生成快照"
			class="com.kueem.webgame.game.action.game.ChatAction" method="findSnapshot">
			<param fieldName="snapshotId" tag="1" fieldType="string" />
		</toServer>
	</protocol>

	<!-- id 快照ID snapshot 快照 -->
	<protocol id="0x00050502" alias="snapshotInfo">
		<toClient desc="快照信息">
			<param fieldName="snapshotId" tag="1" fieldType="string" />
			<param fieldName="snapshot" tag="2" fieldType="string" />
		</toClient>
	</protocol>

	<!-- id 道具或者装备ID -->
	<protocol id="0x00050602" alias="generateSnapshotId">
		<toServer desc="请求快照ID"
			class="com.kueem.webgame.game.action.game.ChatAction" method="generateSnapshotId">
			<param fieldName="number" tag="1" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x00050702" alias="syncSnapshotId">
		<toClient desc="返回快照ID">
			<param fieldName="snapshotIds" tag="1" fieldType="string"
				repeated="true" />
		</toClient>
	</protocol>


	<protocol id="0x00050802" alias="syncCYL">
		<toClient desc="同步传音令免费次数">
			<param fieldName="num" tag="1" fieldType="int32" />
		</toClient>
		<toServer desc="请求传音令免费次数"
			class="com.kueem.webgame.game.action.game.ChatAction" method="syncCYL">
		</toServer>
	</protocol>

</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/mount.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="mount">

	<protocol id="0x00170102" alias="sync">
		<toServer desc="同步坐骑信息"
			class="com.kueem.webgame.game.action.game.MountAction" method="sync">
		</toServer>
	</protocol>

	<protocol id="0x00170202" alias="syncResult">
		<toClient desc="返回坐骑信息" proto="true"
			messageClass="com.kueem.webgame.game.protobuf.MountProtoBuf.MountProto">
		</toClient>
	</protocol>

	<protocol id="0x00170302" alias="install">
		<toServer desc="装备上坐骑"
			class="com.kueem.webgame.game.action.game.MountAction" method="install">
			<param fieldName="incId" tag="1" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x00170402" alias="uninstall">
		<toServer desc="卸载坐骑"
			class="com.kueem.webgame.game.action.game.MountAction" method="uninstall">
			<param fieldName="incId" tag="1" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x00170502" alias="free">
		<toServer desc="放生坐骑"
			class="com.kueem.webgame.game.action.game.MountAction" method="free">
			<param fieldName="incId" tag="1" fieldType="int32" />
		</toServer>

	</protocol>

	<protocol id="0x00170602" alias="feed">
		<toServer desc="喂养坐骑坐骑"
			class="com.kueem.webgame.game.action.game.MountAction" method="feed">
			<param fieldName="incId" tag="1" fieldType="int32" />
			<param fieldName="bagIndex" tag="2" fieldType="int32" repeated="true" />
			<param fieldName="numberList" tag="3" fieldType="int32"
				repeated="true" />
		</toServer>
	</protocol>

	<protocol id="0x00170702" alias="advance">
		<toServer desc="坐骑进阶"
			class="com.kueem.webgame.game.action.game.MountAction" method="advance">
			<param fieldName="incId" tag="1" fieldType="int32" />
			<param fieldName="perfect" tag="2" fieldType="bool" />
			<param fieldName="autoBuy" tag="3" fieldType="bool" />
			<param fieldName="bindFirst" tag="4" fieldType="bool" />
			<param fieldName="type" tag="5" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x00170802" alias="fuse">
		<toServer desc="坐骑融合"
			class="com.kueem.webgame.game.action.game.MountAction" method="fuse">
			<param fieldName="masterId" tag="1" fieldType="int32" />
			<param fieldName="slaveId" tag="2" fieldType="int32" />
			<param fieldName="attrType" tag="3" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x00170902" alias="huanhua">
		<toServer desc="坐骑幻化"
			class="com.kueem.webgame.game.action.game.MountAction" method="huanhua">
			<param fieldName="incId" tag="1" fieldType="int32" />
			<param fieldName="targetId" tag="2" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x00170A02" alias="xisui">
		<toServer desc="坐骑洗髓（刷新数值）"
			class="com.kueem.webgame.game.action.game.MountAction" method="xisui">
			<param fieldName="incId" tag="1" fieldType="int32" />
			<param fieldName="autoBuy" tag="2" fieldType="bool" />
			<param fieldName="bindFirst" tag="3" fieldType="bool" />
		</toServer>
	</protocol>

	<protocol id="0x00170B02" alias="replace">
		<toServer desc="坐骑洗髓（替换数值）"
			class="com.kueem.webgame.game.action.game.MountAction" method="replace">
			<param fieldName="incId" tag="1" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x00170C02" alias="perfectAdvanceInfo">
		<toClient desc="完美进阶反馈数据">
			<param fieldName="success" tag="1" fieldType="bool" desc="是否成功" />
			<param fieldName="level" tag="2" fieldType="int32" desc="当前等级" />
			<param fieldName="perfect" tag="3" fieldType="int32" desc="完美度(整数)" />
			<param fieldName="itemCount" tag="4" fieldType="int32" desc="消耗道具数量" />
			<param fieldName="itemId" tag="5" fieldType="int32" desc="消耗道具ID" />
			<param fieldName="cash" tag="6" fieldType="int32" desc="消耗铜钱数量" />
		</toClient>
	</protocol>

	<protocol id="0x00170D02" alias="mount">
		<toServer desc="骑马"
			class="com.kueem.webgame.game.action.game.MountAction" method="mount">
		</toServer>
	</protocol>

	<protocol id="0x00170E02" alias="reincar">
		<toServer desc="坐骑转生"
			class="com.kueem.webgame.game.action.game.MountAction" method="reincar">
			<param fieldName="incId" tag="1" fieldType="int32" />
			<param fieldName="autoBuy" tag="2" fieldType="bool" />
			<param fieldName="bindFirst" tag="3" fieldType="bool" />
		</toServer>
	</protocol>

</config>

=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/mystery_shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="mystery_shop">
    <protocol id="0x00290102" alias="mysteryShopInfo">
        <toClient desc="神秘商城的基本信息返回">
            <param fieldName="Integral" tag="1" fieldType="int32" />
            <param fieldName="Luckly" tag="2" fieldType="int32" />
            <param fieldName="FreeTime" tag="3" fieldType="int32" /><!-- 今天已经刷新的次数 -->
        </toClient>
        <toServer desc="神秘商城的基本信息" class="com.kueem.webgame.game.action.game.MysteryShopAction" method="mysteryShopInfo">
        </toServer>
    </protocol>


    <protocol id="0x00290202" alias="syncShopData">
        <toClient desc="神秘商品数据返回">
            <param fieldName="dataIds" tag="1" fieldType="int32" repeated="true" />
            <param fieldName="states" tag="2" fieldType="int32" repeated="true" />
        </toClient>
        <toServer desc="神秘商品数据" class="com.kueem.webgame.game.action.game.MysteryShopAction" method="syncShopData">
        </toServer>
    </protocol>

    <protocol id="0x00290302" alias="storageShopData">
        <toClient desc="神秘商品仓库数据" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserBagProtobuf.UserBag">
        </toClient>
        <toServer desc="神秘商品仓库数据" class="com.kueem.webgame.game.action.game.MysteryShopAction" method="storageShopData">
        </toServer>
    </protocol>


    <protocol id="0x00290402" alias="luckData">
        <toClient desc="">
            <param fieldName="userId" tag="1" fieldType="string" desc="用户id" />
            <param fieldName="userName" tag="2" fieldType="string" desc="用户名字" />
            <param fieldName="camp" tag="3" fieldType="int32" desc="用户阵营" />
            <param fieldName="mysteryId" tag="4" fieldType="int32" desc="mystery_shop表里的id" />
        </toClient>
    </protocol>

    <protocol id="0x00290502" alias="refreshShop">
        <toClient desc="刷新神秘数据返回">
            <param fieldName="state" tag="1" fieldType="int32" />
        </toClient>
        <toServer desc="刷新神秘数据 " class="com.kueem.webgame.game.action.game.MysteryShopAction" method="refreshShop">
            <param fieldName="refreshType" tag="1" fieldType="int32" desc="0:单个、1:多个" />
        </toServer>
    </protocol>

    <protocol id="0x00290602" alias="buyItem">
        <toClient desc="购买神秘物品返回">
            <param fieldName="state" tag="1" fieldType="int32" />
        </toClient>
        <toServer desc="购买神秘物品 " class="com.kueem.webgame.game.action.game.MysteryShopAction" method="buyItem">
            <param fieldName="itemId" tag="1" fieldType="int32" />
        </toServer>
    </protocol>


    <protocol id="0x00290702" alias="changeItem">
        <toClient desc="积好换物品物品返回">
            <param fieldName="state" tag="1" fieldType="int32" />
        </toClient>
        <toServer desc="积好换物品物品 " class="com.kueem.webgame.game.action.game.MysteryShopAction" method="changeItem">
            <param fieldName="itemId" tag="1" fieldType="int32" />
        </toServer>
    </protocol>


    <protocol id="0x00290802" alias="getItem">
        <toServer desc="仓库提取 " class="com.kueem.webgame.game.action.game.MysteryShopAction" method="getItem">
            <param fieldName="bagIndex" tag="1" fieldType="int32" />
        </toServer>
    </protocol>

    <protocol id="0x00290902" alias="getAllItem">
        <toServer desc="仓库提取 " class="com.kueem.webgame.game.action.game.MysteryShopAction" method="getAllItem">
        </toServer>
    </protocol>

</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/spirit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="spirit">

    <protocol id="0x00150102" alias="sync">
        <toServer desc="战纹系统同步" class="com.kueem.webgame.game.action.game.SpiritAction" method="sync">
        </toServer>
    </protocol>


    <!-- 战纹信息,战魂信息,机信息,战魂最大等级,当前修炼的战纹,当前修炼的战纹等级,当前修炼的开始时间 战纹套件的等级，战魂套件的等级 -->
    <protocol id="0x00150202" alias="syncInfo">
        <toClient desc="战纹信息">
            <param fieldName="vein" tag="1" fieldType="int32" repeated="true" />
            <param fieldName="soul" tag="2" fieldType="int32" repeated="true" />
            <param fieldName="secret" tag="3" fieldType="int32" repeated="true" />
            <param fieldName="soul_max" tag="4" fieldType="int32" repeated="true" />
            <param fieldName="practice_vein" tag="5" fieldType="int32" />
            <param fieldName="practice_level" tag="6" fieldType="int32" />
            <param fieldName="practice_time" tag="7" fieldType="int64" />
            <param fieldName="secret_count" tag="8" fieldType="int32" />
            <param fieldName="vein_suit_level" tag="9" fieldType="int32" />
            <param fieldName="soul_suit_level" tag="10" fieldType="int32" />
        </toClient>
    </protocol>

    <!-- type 0 - 7 -->
    <protocol id="0x00150302" alias="practice">
        <toServer desc="战纹修炼" class="com.kueem.webgame.game.action.game.SpiritAction" method="practice">
            <param fieldName="type" tag="1" fieldType="int32" />
        </toServer>
    </protocol>

    <!-- type 1 加速一个小时 2 直接完成 -->
    <protocol id="0x00150402" alias="speedUpPractice">
        <toServer desc="战纹加速" class="com.kueem.webgame.game.action.game.SpiritAction" method="speedUpPractice">
            <param fieldName="type" tag="1" fieldType="int32" />
        </toServer>
    </protocol>


    <!-- 1 类型 2保护符数量 3是否自动购买 -->
    <protocol id="0x00150502" alias="soulUp">
        <toServer desc="战魂进化" class="com.kueem.webgame.game.action.game.SpiritAction" method="soulUp">
            <param fieldName="type" tag="1" fieldType="int32" />
            <param fieldName="baohufuNumber" tag="2" fieldType="int32" />
            <param fieldName="autoBuy" tag="3" fieldType="bool" />
        </toServer>
    </protocol>


    <!-- 1 类型 -->
    <protocol id="0x00150602" alias="secretUp">
        <toServer desc="感悟天机" class="com.kueem.webgame.game.action.game.SpiritAction" method="secretUp">
            <param fieldName="type" tag="1" fieldType="int32" />
        </toServer>
    </protocol>

    <!-- 1 类型 -->
    <protocol id="0x00150702" alias="soulLevelExpand">
        <toServer desc="战魂突破" class="com.kueem.webgame.game.action.game.SpiritAction" method="soulLevelExpand">
            <param fieldName="type" tag="1" fieldType="int32" />
            <param fieldName="tupodanNumber" tag="2" fieldType="int32" />
        </toServer>
    </protocol>


    <protocol id="0x00150802" alias="notice">
        <toClient desc="通知客户端 可以修炼战纹">
            <param fieldName="flag" tag="1" fieldType="bool" />
        </toClient>
    </protocol>

    <protocol id="0x00150902" alias="opRet">
        <toClient desc="一些操作返回信息">
            <param fieldName="ret" tag="1" fieldType="int32" desc="操作结果 1 修炼的时候收到修炼的请求 2 没修炼的时候收到加速请求" />
        </toClient>
    </protocol>

</config>
