=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/message.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config (include*, protocol+)>
<!ATTLIST config namespace CDATA #REQUIRED>
<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>
<!ELEMENT protocol (toClient?,toServer?,returnMsg?)>
<!ATTLIST protocol 
    id CDATA #REQUIRED
    alias CDATA #IMPLIED
>
<!ELEMENT toClient (param*)>
<!ATTLIST toClient 
    desc CDATA #REQUIRED
    proto (true|false) "false"
    messageClass CDATA #IMPLIED
>
<!ELEMENT toServer (param*)>
<!ATTLIST toServer
    desc CDATA #REQUIRED
    proto (true|false) "false"
    class CDATA #REQUIRED
    messageClass CDATA #IMPLIED
    method CDATA #REQUIRED
>
<!ELEMENT returnMsg (msg+)>
<!ELEMENT param EMPTY>
<!ATTLIST param
    tag (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32) #REQUIRED
    fieldName CDATA #REQUIRED
    fieldType (string|int32|int64|bytes|bool) #REQUIRED
    repeated (true|false) "false"
    desc CDATA #IMPLIED
>
<!ELEMENT msg EMPTY>
<!ATTLIST msg 
    id CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/bag.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="bag">

    <protocol id="0x000B0302" alias="combine">
        <toServer desc="合并" class="com.kueem.webgame.game.action.game.BagAction" method="combine">
        </toServer>
    </protocol>

    <protocol id="0x000B0402" alias="trim">
        <toServer desc="整理" class="com.kueem.webgame.game.action.game.BagAction" method="trim">
        </toServer>
    </protocol>

    <protocol id="0x000B0502" alias="sell">
        <toServer desc="出售" class="com.kueem.webgame.game.action.game.BagAction" method="sell">
            <param fieldName="index" tag="1" fieldType="int32" />
        </toServer>
    </protocol>

    <protocol id="0x000B0602" alias="split">
        <toServer desc="拆分" class="com.kueem.webgame.game.action.game.BagAction" method="split">
            <param fieldName="index" tag="1" fieldType="int32" />
            <param fieldName="num" tag="2" fieldType="int32" />
        </toServer>
    </protocol>

    <protocol id="0x000B0702" alias="destroy">
        <toServer desc="摧毁" class="com.kueem.webgame.game.action.game.BagAction" method="destroy">
            <param fieldName="index" tag="1" fieldType="int32" />
        </toServer>
    </protocol>

    <protocol id="0x000B0802" alias="info">
        <toServer desc="获取背包数据" class="com.kueem.webgame.game.action.game.BagAction" method="info">
            <param fieldName="page" tag="1" fieldType="int32" />
        </toServer>
    </protocol>

    <protocol id="0x000B0C02" alias="move">
        <toServer desc="拖动" class="com.kueem.webgame.game.action.game.BagAction" method="move">
            <param fieldName="start" tag="1" fieldType="int32" />
            <param fieldName="target" tag="2" fieldType="int32" />
        </toServer>
    </protocol>

    <protocol id="0x000B0D02" alias="open">
        <toServer desc="开格子" class="com.kueem.webgame.game.action.game.BagAction" method="open">
            <param fieldName="num" tag="1" fieldType="int32" />
        </toServer>
    </protocol>

    <protocol id="0x000B0E02" alias="use">
        <toServer desc="使用道具" class="com.kueem.webgame.game.action.game.BagAction" method="use">
            <param fieldName="index" tag="1" fieldType="int32" />
            <param fieldName="num" tag="2" fieldType="int32" />
        </toServer>
    </protocol>

    <protocol id="0x000B0B02" alias="sync">
        <toClient desc="同步整个背包数据" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserBagProtobuf.UserBag">
        </toClient>
    </protocol>

    <protocol id="0x000B0F02" alias="syncPart">
        <toClient desc="同步部分背包数据" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserBagProtobuf.UserBag">
        </toClient>
    </protocol>
</config>

=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/manage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="manage">
    <protocol id="0x00000108" alias="dailyReset">
        <toClient desc="每日重置协议返回">
            <param fieldName="result" tag="1" fieldType="int32" desc="重置返回值，1：重置成功，0：重置失败" />
        </toClient>
        <toServer desc="每日重置协议" class="com.kueem.webgame.game.action.manage.ManageAction" method="dailyReset">
            <param fieldName="ignore" tag="1" fieldType="bool" desc="是否忽略已重置的情况" />
        </toServer>
    </protocol>
    <protocol id="0x00000208" alias="maintain">
        <toClient desc="服务器挂维护返回">
            <param fieldName="msg" tag="1" fieldType="string" desc="返回消息" />
        </toClient>
        <toServer desc="服务器挂维护" class="com.kueem.webgame.game.action.manage.ManageAction" method="maintain">
        </toServer>
    </protocol>
    <protocol id="0x00000308" alias="running">
        <toClient desc="服务器恢复运行返回">
            <param fieldName="msg" tag="1" fieldType="string" desc="返回消息" />
        </toClient>
        <toServer desc="服务器恢复运行" class="com.kueem.webgame.game.action.manage.ManageAction" method="running">
        </toServer>
    </protocol>
    <protocol id="0x00000408" alias="shutdown">
        <toClient desc="服务器关闭前准备返回">
            <param fieldName="step" tag="1" fieldType="int32" desc="返回步骤" />
            <param fieldName="msg" tag="2" fieldType="string" desc="返回消息 " />
        </toClient>
        <toServer desc="服务器关闭前准备" class="com.kueem.webgame.game.action.manage.ManageAction" method="shutdown">
        </toServer>
    </protocol>
</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/mail.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="mail">
    <protocol id="0x00100102" alias="getMail">
        <toServer desc="邮件系统：获取邮件列表" class="com.kueem.webgame.game.action.game.MailAction" method="getMail">
            <param fieldName="type" tag="1" fieldType="int32" />
            <param fieldName="timestamp" tag="2" fieldType="int64" />
        </toServer>
    </protocol>
    <protocol id="0x00100202" alias="syncMailResult">
        <toClient desc="同步用户邮件" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserMailBuffers.UserMail">
        </toClient>
    </protocol>
    <protocol id="0x00100302" alias="newMailNotice">
        <toClient desc="通知用户收到新邮件">
            <param fieldName="num" tag="1" fieldType="int64" />
        </toClient>
    </protocol>
    <protocol id="0x00100402" alias="sendUserMail">
        <toServer desc="邮件系统：用户发送邮件" class="com.kueem.webgame.game.action.game.MailAction" method="sendUserMail">
            <param fieldName="reciever_name" tag="1" fieldType="string" />
            <param fieldName="title" tag="2" fieldType="string" />
            <param fieldName="content" tag="3" fieldType="string" />
            <param fieldName="item_indexes" tag="4" fieldType="int32" repeated="true" />
            <param fieldName="coin" tag="5" fieldType="int32" />
        </toServer>
    </protocol>
    <protocol id="0x00100602" alias="fetchAttachment">
        <toServer desc="邮件系统：提取附件" class="com.kueem.webgame.game.action.game.MailAction" method="fetchAttachment">
            <param fieldName="mail_id" tag="1" fieldType="int32" />
            <param fieldName="position" tag="2" fieldType="int32" />
        </toServer>
    </protocol>
    <protocol id="0x00100702" alias="deleteMail">
        <toServer desc="邮件系统：删除邮件" class="com.kueem.webgame.game.action.game.MailAction" method="deleteMail">
            <param fieldName="mail_ids" tag="1" fieldType="int32" repeated="true" />
            <param fieldName="type" tag="2" fieldType="int32" />
            <param fieldName="timestamp" tag="3" fieldType="int64" />
        </toServer>
    </protocol>
    <protocol id="0x00100802" alias="sendMailResult">
        <toClient desc="发送邮件的结果">
            <param fieldName="result" tag="1" fieldType="bool" />
        </toClient>
    </protocol>
    <protocol id="0x00100902" alias="autoFilter">
        <toServer desc="邮件系统：设置自动过滤黑名单" class="com.kueem.webgame.game.action.game.MailAction" method="autoFilter">
            <param fieldName="flag" tag="1" fieldType="bool" />
        </toServer>
    </protocol>
    <protocol id="0x00100A02" alias="deleteAfterFetch">
        <toServer desc="邮件系统：设置提取附件后删除邮件" class="com.kueem.webgame.game.action.game.MailAction" method="deleteAfterFetch">
            <param fieldName="flag" tag="1" fieldType="bool" />
        </toServer>
    </protocol>
    <protocol id="0x00100B02" alias="getMailContent">
        <toServer desc="邮件系统：获取邮件内容" class="com.kueem.webgame.game.action.game.MailAction" method="getMailContent">
            <param fieldName="mail_id" tag="1" fieldType="int32" />
        </toServer>
    </protocol>
    <protocol id="0x00100C02" alias="mailContentReturn">
        <toClient desc="返回邮件的内容">
            <param fieldName="content" tag="1" fieldType="string" />
            <param fieldName="mail_id" tag="2" fieldType="int32" />
        </toClient>
    </protocol>
    <protocol id="0x00100D02" alias="getNewMail">
        <toServer desc="邮件系统：获取新邮件列表" class="com.kueem.webgame.game.action.game.MailAction" method="getNewMail">
            <param fieldName="beginTime" tag="1" fieldType="int64" />
            <param fieldName="endTime" tag="2" fieldType="int64" />
        </toServer>
    </protocol>
    <protocol id="0x00100E02" alias="fetchAll">
        <toClient desc="返回已提取附件的邮件">
            <param fieldName="ids" tag="1" fieldType="int32" repeated="true" />
        </toClient>
        <toServer desc="邮件系统：一键提取所有邮件中的附件" class="com.kueem.webgame.game.action.game.MailAction" method="fetchAll">
        </toServer>
    </protocol>
</config>

=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/hero.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="hero">
    <protocol id="0x000C0102" alias="equipsInfo">
        <toServer desc="人物属性：获取装备信息" class="com.kueem.webgame.game.action.game.HeroAction" method="equipsInfo">
        </toServer>
    </protocol>
    <protocol id="0x000C0202" alias="equipInfoResult">
        <toClient desc="返回用户装备数据" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserEquipProtobuf.Equips">
        </toClient>
    </protocol>
    <protocol id="0x000C0302" alias="equip">
        <toServer desc="人物属性：穿戴装备" class="com.kueem.webgame.game.action.game.HeroAction" method="equip">
            <param fieldName="index" tag="1" fieldType="int32" />
            <param fieldName="pos" tag="2" fieldType="int32" />
        </toServer>
    </protocol>
    <protocol id="0x000C0402" alias="remove">
        <toServer desc="人物属性：从人物身上移除装备,放入背包" class="com.kueem.webgame.game.action.game.HeroAction" method="remove">
            <param fieldName="pos" tag="1" fieldType="int32" />
            <param fieldName="index" tag="2" fieldType="int32" />
        </toServer>
    </protocol>
    <protocol id="0x000C0502" alias="info">
        <toServer desc="人物属性：获取人物属性" class="com.kueem.webgame.game.action.game.HeroAction" method="info">
        </toServer>
    </protocol>
    <protocol id="0x000C0702" alias="showConfig">
        <toServer desc="人物属性：三种时装的显示/隐藏" class="com.kueem.webgame.game.action.game.HeroAction" method="showConfig">
            <param fieldName="wing" tag="1" fieldType="int32" />
            <param fieldName="clothes" tag="2" fieldType="int32" />
            <param fieldName="weapon" tag="3" fieldType="int32" />
        </toServer>
    </protocol>
    <protocol id="0x000C0A02" alias="updateEquipInfo">
        <toClient desc="更新部分用户装备数据" proto="true" messageClass="com.kueem.webgame.game.protobuf.UserEquipProtobuf.Equips">
        </toClient>
    </protocol>

    <!--宝石套装，强化套装，……………… -->
    <protocol id="0x000C0B02" alias="getGemSuit">
        <toClient desc="宝石套装 参数">
            <param tag="1" fieldType="int32" fieldName="" desc="当前宝石套装的id" />
            <param tag="2" fieldType="int32" fieldName="" desc="当前拥有的宝石个数 " />
        </toClient>
        <toServer desc="宝石套装 " class="com.kueem.webgame.game.action.game.HeroAction" method="getGemSuit">
        </toServer>
    </protocol>

    <protocol id="0x000C0C02" alias="getStrengthEquipSuit">
        <toClient desc="装备强化套装参数">
            <param tag="1" fieldType="int32" fieldName="" desc="当前宝石套装的id" />
            <param tag="2" fieldType="int32" fieldName="" desc="当前拥有的宝石个数" />
        </toClient>
        <toServer desc="装备套装 " class="com.kueem.webgame.game.action.game.HeroAction" method="getStrengthEquipSuit">
        </toServer>
    </protocol>

    <protocol id="0x000C0D02" alias="getEquipSuit">
        <toClient desc="装备套装参数">
            <param tag="1" fieldType="int32" fieldName="" desc="当前宝石套装的id" />
        </toClient>
        <toServer desc="装备套装 " class="com.kueem.webgame.game.action.game.HeroAction" method="getEquipSuit">
        </toServer>
    </protocol>


</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/activity.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="activity">
	<protocol id="0x001F0102" alias="gain">
		<toServer desc="奖励领取"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="gain">
			<param fieldName="actid" tag="1" fieldType="int32" />
			<param fieldName="index" tag="2" fieldType="int32" />
		</toServer>
	</protocol>
	<protocol id="0x001F0202" alias="sync">
		<toServer desc="活动同步"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="sync">
			<param fieldName="actid" tag="1" fieldType="int32" />
		</toServer>
	</protocol>
	<protocol id="0x001F0302" alias="syncResult">
		<toClient desc="活动同步返回">
			<param fieldName="indexs" tag="1" fieldType="int32" repeated="true" />
			<param fieldName="canGains" tag="2" fieldType="bool" repeated="true" />
			<param fieldName="status" tag="3" fieldType="int32" repeated="true" />
			<param fieldName="startTime" tag="4" fieldType="int32" />
			<param fieldName="duration" tag="5" fieldType="int32" />
			<param fieldName="actid" tag="6" fieldType="int32" />
		</toClient>
	</protocol>

	<protocol id="0x001F0402" alias="canRewardNeiceJunling">
		<toClient desc="返回内测军令福利是否已经领取了">
			<param fieldName="canReward" tag="1" fieldType="bool" desc="是否已经领取了" />
		</toClient>
		<toServer desc="请求是否可以领取军令"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="canRewardNeiceJunling">
		</toServer>
	</protocol>
	<protocol id="0x001F0502" alias="rewardNeiceJunling">
		<toClient desc="返回内测军令福利是否已经领取了">
			<param fieldName="canReward" tag="1" fieldType="bool" desc="是否成功" />
		</toClient>
		<toServer desc="领取奖励"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="rewardNeiceJunling">
		</toServer>
	</protocol>

	<protocol id="0x001F0602" alias="syncActivityLogin">
		<toClient desc="活动信息">
			<param fieldName="get111" tag="1" fieldType="int32" repeated="true" />
			<param fieldName="login" tag="2" fieldType="int32" repeated="true" />
		</toClient>
		<toServer desc="请求活动信息"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="requestActivityLogin">
		</toServer>
	</protocol>
	<protocol id="0x001F0702" alias="getActivityLoginReward">
		<toServer desc="领取奖励"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityLoginReward">
			<param fieldName="day" tag="1" fieldType="int32" />
		</toServer>
	</protocol>


	<protocol id="0x001F0802" alias="getActivityEquipSuit">
		<toClient desc="同步活动装备领取状态">
			<param fieldName="state" tag="1" fieldType="int32" repeated="true" /> <!-- 0 / 1 -->
		</toClient>
		<toServer desc="领取"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityEquipSuit">
			<param fieldName="index" tag="1" fieldType="int32" />
		</toServer>
	</protocol>
	<protocol id="0x001F0902" alias="getActivityZhanWen">
		<toClient desc="同步活动战纹领取状态">
			<param fieldName="state" tag="1" fieldType="int32" repeated="true" /> <!-- 0 / 1 -->
		</toClient>
		<toServer desc="领取"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityZhanWen">
			<param fieldName="index" tag="1" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x001F0A02" alias="getActivityRank">
		<toClient desc="同步排行">
			<param fieldName="index" tag="1" fieldType="int32" /> <!-- 1:等级 2:战力 -->
			<param fieldName="name" tag="2" fieldType="string" repeated="true" />
			<param fieldName="camp" tag="3" fieldType="int32" repeated="true" />
			<param fieldName="level_force" tag="4" fieldType="int32"
				repeated="true" />
		</toClient>
		<toServer desc="请求排行"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityRank">
			<param fieldName="index" tag="1" fieldType="int32" /><!-- 1:等级 2:战力 -->
		</toServer>
	</protocol>
	<protocol id="0x001F0B02" alias="getActivityTopUp">
		<toClient desc="同步充值">
			<param fieldName="state" tag="1" fieldType="int32" repeated="true" /> <!-- 0 / 1 -->
		</toClient>
		<toServer desc="领取"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityTopUp">
			<param fieldName="index" tag="1" fieldType="int32" /><!-- 1:等级 2:战力 -->
		</toServer>
	</protocol>


	<protocol id="0x001F0C02" alias="getActivityTopUpRank">
		<toClient desc="同步充值排行">
			<param fieldName="name" tag="1" fieldType="string" repeated="true" />
			<param fieldName="gender" tag="2" fieldType="string" repeated="true" />
			<param fieldName="camp" tag="3" fieldType="int32" repeated="true" />
			<param fieldName="payNum" tag="4" fieldType="int32" repeated="true" />
		</toClient>
		<toServer desc="请求排行"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityTopUpRank">
		</toServer>
	</protocol>


	<protocol id="0x001F0D02" alias="recoverLogin">
		<toServer desc="在活动期间内可花费50元宝/天补回之前未登陆的天数"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="recoverLogin">
			<param fieldName="day" tag="1" fieldType="int32" />
		</toServer>
	</protocol>

	<protocol id="0x001F0F02" alias="getActivityGetCoinInfo">
		<toClient desc="同步发放元宝数据">
			<param fieldName="hadGet" tag="1" fieldType="int32" /><!-- 已领取 -->
		</toClient>
		<toServer desc="请求排行"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityGetCoinInfo">
		</toServer>
	</protocol>

	<protocol id="0x001F1002" alias="getActivityCoin">
		<toServer desc="领取活动发放的50元宝"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityCoin">
		</toServer>
	</protocol>

	<protocol id="0x001F1102" alias="getActivityBuyWingsInfo">
		<toClient desc="同步已经购翅膀的数量">
			<param fieldName="hadBuyCount" tag="1" fieldType="int32" />
		</toClient>
		<toServer desc="请求已经购翅膀的数量"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getActivityLimitBuyItemInfo">
		</toServer>
	</protocol>


	<protocol id="0x001F1202" alias="buyWings">
		<toServer desc="购买翅膀"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="buyWings">
			<param fieldName="actid" tag="1" fieldType="int32" /><!-- 翅膀的id -->
		</toServer>
	</protocol>


	<protocol id="0x001F1302" alias="requestPayforInfo">
		<toClient desc="同步充值活的信息">
			<param fieldName="days" tag="1" fieldType="int32" repeated="true" /><!--充值状态1：已充，2已领 -->
			<param fieldName="lastPayTime" tag="2" fieldType="string" /><!-- 
				最后一次充值时间 -->
		</toClient>
		<toServer desc="请求同步充值活的信息"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="requestPayforInfo">
		</toServer>
	</protocol>

	<protocol id="0x001F1402" alias="getPayForActivityReward">
		<toServer desc="领取充值活动奖励"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getPayForActivityReward">
			<param fieldName="actid" tag="1" fieldType="int32" /><!--天 -->
		</toServer>
	</protocol>

	<protocol id="0x001F1502" alias="requestSixGiftInfo">
		<toClient desc="同步三天六个物品　活动">
			<param fieldName="state" tag="1" fieldType="int32" repeated="true" /><!--0未领,1错过了领取,2已领取 -->
			<param fieldName="endTime" tag="2" fieldType="string" /><!--倒计时时间 -->
			<param fieldName="times" tag="3" fieldType="int32" /><!--领取的次数-->
		</toClient>
		<toServer desc="请求同步充值活的信息"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="requestSixGiftInfo">
		</toServer>
	</protocol>

	<protocol id="0x001F1602" alias="getSixGiftRewrad">
		<toClient desc="同步rock到的索引 ">
			<param fieldName="index" tag="1" fieldType="int32" /><!-- 同步到的随机物品索引 -->
		</toClient>

		<toServer desc="领取充值活动奖励"
			class="com.kueem.webgame.game.action.game.ActivityAction" method="getSixGiftRewrad">
		</toServer>
	</protocol>






</config>

=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="system">
    <protocol id="0x00000000" alias="exception">
        <toClient desc="系统异常">
            <param fieldName="code" tag="1" fieldType="int32" />
            <param fieldName="msg" tag="2" fieldType="string" />
        </toClient>
    </protocol>

    <protocol id="0x00000001" alias="login">
        <toClient desc="登陆返回">
            <param fieldName="state" tag="1" fieldType="int32" />
            <param fieldName="uid" tag="2" fieldType="string" />
        </toClient>
        <toServer desc="登陆请求" class="com.kueem.webgame.game.action.sys.SystemAction" method="login">
            <param fieldName="uid" tag="1" fieldType="string" />
            <param fieldName="platform" tag="2" fieldType="string" />
            <param fieldName="session_key" tag="3" fieldType="string" />
            <param fieldName="my_signed_request" tag="4" fieldType="string" />
        </toServer>
    </protocol>

    <protocol id="0x00000003" alias="logout">
        <toClient desc="登出">
            <param fieldName="state" tag="1" fieldType="int32" />
        </toClient>
    </protocol>

    <protocol id="0x00000005" alias="heart">
        <toServer desc="心跳" class="com.kueem.webgame.game.action.sys.SystemAction" method="heart">
        </toServer>
    </protocol>

    <protocol id="0x00000006" alias="serverTime">
        <toClient desc="同步服务器时间返回">
            <param fieldName="server_time" tag="1" fieldType="string" />
        </toClient>
        <toServer desc="同步服务器时间" class="com.kueem.webgame.game.action.sys.SystemAction" method="serverTime">
        </toServer>
    </protocol>

    <protocol id="0x00000007" alias="message">
        <toClient desc="系统消息" proto="true" messageClass="com.kueem.webgame.game.protobuf.MsgBuffers.MsgProto">
        </toClient>
    </protocol>
    <protocol id="0x00000010" alias="debug">
        <toClient desc="返回结果">
            <param tag="1" fieldType="string" desc="结果json" fieldName="result" />
        </toClient>
        <toServer desc="调试用的管理接口" class="com.kueem.webgame.game.action.sys.SystemAction" method="debug">
            <param fieldName="func" tag="1" fieldType="int32" />
        </toServer>
    </protocol>
    <protocol id="0x00000011" alias="logLevel">
        <toClient desc="返回结果">
            <param tag="1" fieldType="bool" desc="操作结果" fieldName="result" />
        </toClient>
        <toServer desc="调整log级别" class="com.kueem.webgame.game.action.sys.SystemAction" method="debug">
            <param fieldName="logName" tag="1" fieldType="string" />
            <param fieldName="level" tag="2" fieldType="string" />
        </toServer>
    </protocol>
    <protocol id="0x00000012">
        <toServer desc="代理登陆" class="com.kueem.webgame.game.action.sys.ProxyAction" method="login">
            <param fieldName="userid" tag="1" fieldType="string" />
            <param fieldName="remoteAddress" tag="2" fieldType="string" />
        </toServer>
    </protocol>
    <protocol id="0x00000013">
        <toClient desc="代理发送">
            <param fieldName="userid" tag="1" fieldType="string" />
            <param fieldName="messageid" tag="2" fieldType="int32" />
            <param fieldName="body" tag="3" fieldType="bytes" />
        </toClient>
        <toServer desc="代理接受" class="com.kueem.webgame.game.action.sys.ProxyAction" method="receive">
            <param fieldName="userid" tag="1" fieldType="string" />
            <param fieldName="messageid" tag="2" fieldType="int32" />
            <param fieldName="body" tag="3" fieldType="bytes" />
        </toServer>
    </protocol>
    <protocol id="0x00000014">
        <toClient desc="代理广播">
            <param fieldName="userid" tag="1" fieldType="string" />
            <param fieldName="messageid" tag="2" fieldType="int32" />
            <param fieldName="body" tag="3" fieldType="bytes" />
        </toClient>
    </protocol>
</config>
