=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/message.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config (include*, protocol+)>
<!ATTLIST config namespace CDATA #REQUIRED>
<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>
<!ELEMENT protocol (toClient?,toServer?,returnMsg?)>
<!ATTLIST protocol 
    id CDATA #REQUIRED
    alias CDATA #IMPLIED
>
<!ELEMENT toClient (param*)>
<!ATTLIST toClient 
    desc CDATA #REQUIRED
    proto (true|false) "false"
    messageClass CDATA #IMPLIED
>
<!ELEMENT toServer (param*)>
<!ATTLIST toServer
    desc CDATA #REQUIRED
    proto (true|false) "false"
    class CDATA #REQUIRED
    messageClass CDATA #IMPLIED
    method CDATA #REQUIRED
>
<!ELEMENT returnMsg (msg+)>
<!ELEMENT param EMPTY>
<!ATTLIST param
    tag (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32) #REQUIRED
    fieldName CDATA #REQUIRED
    fieldType (string|int32|int64|bytes|bool) #REQUIRED
    repeated (true|false) "false"
    desc CDATA #IMPLIED
>
<!ELEMENT msg EMPTY>
<!ATTLIST msg 
    id CDATA #REQUIRED
    value CDATA #REQUIRED
>

=== kitsudog/PacketDoctor/src/main/resources/sniffer/jssg/message/buff.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="buff">
    <protocol id="0x00070102" alias="addBuff">
        <toClient desc="增加了一个buff">
            <param fieldName="bidInMap" tag="1" fieldType="int64" />
            <param fieldName="bid" tag="2" fieldType="int32" />
            <param fieldName="allTime" tag="3" fieldType="int64" />
            <param fieldName="remainTime" tag="4" fieldType="int64" />
            <param fieldName="soldierId" tag="5" fieldType="string" />
            <param fieldName="x" tag="6" fieldType="int32" />
            <param fieldName="y" tag="7" fieldType="int32" />
        </toClient>
    </protocol>

    <protocol id="0x00070202" alias="removeBuff">
        <toClient desc="移除了一个buff">
            <param fieldName="bidInMap" tag="1" fieldType="int64" />
            <param fieldName="bid" tag="2" fieldType="int32" />
            <param fieldName="soldierId" tag="3" fieldType="string" />
        </toClient>
    </protocol>

    <protocol id="0x00070302" alias="changeBuff">
        <toClient desc="由于buff的作用某个目标的属性改变了">
            <param fieldName="bidInMap" tag="1" fieldType="int64" />
            <param fieldName="soldierId" tag="2" fieldType="string" />
            <param fieldName="type" tag="3" fieldType="int32" />
            <param fieldName="changeValue" tag="3" fieldType="int32" />
            <param fieldName="changeAfterValue" tag="3" fieldType="int32" />
        </toClient>
    </protocol>

    <protocol id="0x00070402" alias="refreshBuff">
        <toClient desc="刷新buff时间">
            <param fieldName="incId" tag="1" fieldType="int64" desc="自增ID" />
            <param fieldName="bid" tag="2" fieldType="int32" desc="buff配置ID" />
            <param fieldName="soldierId" tag="3" fieldType="string" desc="用户ID" />
            <param fieldName="allTime" tag="4" fieldType="int64" desc="总时间" />
            <param fieldName="remainTime" tag="5" fieldType="int64" desc="剩余时间" />
            <param fieldName="soldierType" tag="6" fieldType="int32" desc="战士类型" />
        </toClient>
    </protocol>
</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/async_pvp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="async_pvp">
	<protocol id="0x003C0102" alias="firstRankInfo">
		<!-- <toClient desc="排名第一的信息">
			<param fieldName="uid" tag="1" fieldType="string"  repeated="true" desc="当前排名前三的玩家ID"></param>
			<param fieldName="uname" tag="2" fieldType="string"  repeated="true" desc="当前排名前三的玩家名称"></param>
			<param fieldName="ucamp" tag="3" fieldType="int32"  repeated="true" desc="当前排名前三的玩家的阵营"></param>
			<param fieldName="ulevel" tag="4" fieldType="int32"  repeated="true" desc="当前排名前三的玩家的等级"></param>
			<param fieldName="ubody" tag="5" fieldType="int32"  repeated="true" desc="当前排名前三的玩家的BODYID"></param>
			<param fieldName="uweaponId" tag="6" fieldType="int32"  repeated="true" desc="当前排名前三的玩家的WeaponId"></param>
			<param fieldName="ujob" tag="7" fieldType="int32" repeated="true" desc="当前排名前三的玩家的职业"></param>
			<param fieldName="uforce" tag="8" fieldType="int32" repeated="true" desc="当前排名前三的玩家的战斗力"></param>
			<param fieldName="winCount" tag="9" fieldType="int32" repeated="true" desc="当前排名前三的玩家的胜利次数"></param>
			<param fieldName="looseCount" tag="10" fieldType="int32" repeated="true" desc="当前排名前三的玩家的失败次数"></param>
			<param fieldName="winnerId" tag="11" fieldType="string" repeated="true" desc="胜者玩家ID"></param>
			<param fieldName="winnerName" tag="12" fieldType="string" repeated="true" desc="胜者玩家名称"></param>
			<param fieldName="winnerCamp" tag="13" fieldType="int32" repeated="true" desc="胜者玩家的阵营"></param>
			<param fieldName="looserId" tag="14" fieldType="string" repeated="true" desc="输者玩家ID"></param>
			<param fieldName="looserName" tag="15" fieldType="string" repeated="true" desc="输者玩家名称"></param>
			<param fieldName="looserCamp" tag="16" fieldType="int32" repeated="true" desc="输者玩家的阵营"></param>
			<param fieldName="halo_id" tag="17" fieldType="int32"  repeated="true" desc="当前排名前三的玩家的光环"></param>
			<param fieldName="wings_id" tag="18" fieldType="int32"  repeated="true" desc="当前排名前三的玩家的翅膀"></param>
			<param fieldName="title_id" tag="19" fieldType="int32"  repeated="true" desc="当前排名前三的玩家的称号"></param>
			<param fieldName="faction_name" tag="20" fieldType="string"  repeated="true"  desc="当前排名前三的玩家的帮派"></param>
		</toClient> -->
		
		
		<toClient desc="排名第一的信息" proto="true"
            messageClass="Open Declaration com.kueem.webgame.game.protobuf.AsyncPvpProto.firstRankInfo">
        </toClient>
	</protocol>


	<protocol id="0x003C0202" alias="myBattleInfo">
		<toClient desc="个人的战斗信息">
			<param fieldName="isWin" tag="1" fieldType="bool" repeated="true"
				desc="是否赢了"></param>
			<param fieldName="isChallenger" tag="2" fieldType="bool"
				repeated="true" desc="是否是挑战者"></param>
			<param fieldName="rank" tag="3" fieldType="int32" repeated="true"
				desc="挑战结束后排名"></param>
			<param fieldName="rankChange" tag="4" fieldType="int32"
				repeated="true" desc="排名变化情况 1上升 2下降 3不变"></param>
			<param fieldName="targetId" tag="5" fieldType="string"
				repeated="true" desc="对方ID"></param>
			<param fieldName="looserName" tag="6" fieldType="string"
				repeated="true" desc="对方名称"></param>
			<param fieldName="looserCamp" tag="7" fieldType="int32"
				repeated="true" desc="对方阵营"></param>
		</toClient>
	</protocol>


	<protocol id="0x003C0302" alias="rankInfo">
		<toClient desc="异步pvp排名信息">
			<param fieldName="currentPage" tag="1" fieldType="int32" desc="当前页数" />
			<param fieldName="totalPage" tag="2" fieldType="int32" desc="总页数" />
			<param fieldName="urank" tag="3" fieldType="int32" repeated="true"
				desc="排名"></param>
			<param fieldName="uid" tag="4" fieldType="string" repeated="true"
				desc="玩家的ID"></param>
			<param fieldName="uname" tag="5" fieldType="string" repeated="true"
				desc="玩家的姓名"></param>
			<param fieldName="ucamp" tag="6" fieldType="int32" repeated="true"
				desc="玩家的阵营"></param>
			<param fieldName="uforce" tag="7" fieldType="int32" repeated="true"
				desc="玩家的战斗力"></param>
			<param fieldName="ujob" tag="8" fieldType="int32" repeated="true"
				desc="玩家的职业"></param>
		</toClient>
	</protocol>

	<protocol id="0x003C0402" alias="myPvpInfo">
		<toClient desc="个人PVP信息">
			<param fieldName="rank" tag="1" fieldType="int32" desc="排名信息"></param>
			<param fieldName="pvpCount" tag="2" fieldType="int32" desc="今日挑战次数"></param>
			<param fieldName="challengeRefreshTime" tag="3" fieldType="string"
				desc="挑战冷却时间"></param>
			<param fieldName="totalAuraReward" tag="4" fieldType="int32" desc="奖励累计的灵气"></param>
            <param fieldName="totalCashReward" tag="5" fieldType="int32" desc="奖励累计的铜钱"></param>
			<param fieldName="pvpBuyCount" tag="6" fieldType="int32" desc="购买多少次了"></param>
		</toClient>
	</protocol>



	<protocol id="0x003C0502" alias="requestAsyncPvpInfo">
		<!-- 1 同步个人的PVP信息 2同步排名第一的信息 3同步个人的战斗信息 4可战斗的列表 -->
		<toServer class="com.kueem.webgame.game.action.game.AsyncPvpAction"
			desc="请求异步PVP信息" method="pvpInfo"></toServer>
	</protocol>


	<protocol id="0x003C0602" alias="requestRankInfo">
		<toServer class="com.kueem.webgame.game.action.game.AsyncPvpAction"
			desc="请求同步排名信息" method="rankInfo">
			<param fieldName="page" tag="1" fieldType="int32" desc="页数" />
		</toServer>
	</protocol>


	<protocol id="0x003C0702" alias="challenge">
		<toClient desc="请求挑战结果">
			<param fieldName="ret" tag="1" fieldType="bool" desc="是否可以挑战"></param>
		</toClient>
		<!-- 1 同步排行信息 -->
		<toServer class="com.kueem.webgame.game.action.game.AsyncPvpAction"
			desc="请求挑战" method="challenge">
			<param fieldName="targetId" tag="1" fieldType="string" desc="挑战对象" />
		</toServer>
	</protocol>


	<protocol id="0x003C0802" alias="challengeRet">
		<toClient desc="挑战结果">
			<param fieldName="isWin" tag="1" fieldType="bool" desc="是否成功"></param>
			<param fieldName="cash" tag="2" fieldType="int32" desc="获得铜币"></param>
			<param fieldName="rank" tag="3" fieldType="int32" desc="排名"></param>
			<param fieldName="tname" tag="4" fieldType="string" desc="目标名称"></param>
			<param fieldName="tcamp" tag="5" fieldType="int32" desc="目标阵营"></param>
			<param fieldName="initiative" tag="6" fieldType="bool" desc="是否玩家主动退出" />
			<param fieldName="arua" tag="7" fieldType="int32" desc="获得灵气" />
		</toClient>
	</protocol>

	<protocol id="0x003C0902" alias="reward">
		<!-- 1 同步个人的PVP信息 -->
		<toServer class="com.kueem.webgame.game.action.game.AsyncPvpAction"
			desc="领奖" method="reward">
		</toServer>
	</protocol>


	<protocol id="0x003C0A02" alias="coolDown">
		<!-- 1 同步个人的PVP信息 -->
		<toServer class="com.kueem.webgame.game.action.game.AsyncPvpAction"
			desc="快速冷却" method="coolDown">
		</toServer>
	</protocol>

	<protocol id="0x003C0B02" alias="buyPvpCount">
		<!-- 1 同步个人的PVP信息 -->
		<toServer class="com.kueem.webgame.game.action.game.AsyncPvpAction"
			desc="购买挑战次数" method="buyPvpCount">
		</toServer>
	</protocol>

	<protocol id="0x003C0C02" alias="canChallengeList">
		<toClient desc="可挑战的列表">
			<param fieldName="urank" tag="1" fieldType="int32" repeated="true"
				desc="排名"></param>
			<param fieldName="uid" tag="2" fieldType="string" repeated="true"
				desc="玩家的ID"></param>
			<param fieldName="uname" tag="3" fieldType="string" repeated="true"
				desc="玩家的姓名"></param>
			<param fieldName="ucamp" tag="4" fieldType="int32" repeated="true"
				desc="玩家的阵营"></param>
			<param fieldName="ulevel" tag="5" fieldType="int32" repeated="true"
				desc="玩家的等级"></param>
			<param fieldName="ujob" tag="6" fieldType="int32" repeated="true"
				desc="玩家的职业"></param>
			<param fieldName="uforce" tag="7" fieldType="int32" repeated="true"
				desc="玩家的战斗力"></param>
			<param fieldName="ubodyID" tag="8" fieldType="int32" repeated="true"
				desc="玩家的bodyID"></param>
			<param fieldName="uweaponID" tag="9" fieldType="int32"
				repeated="true" desc="玩家的weaponID"></param>
			<param fieldName="uwinCount" tag="10" fieldType="int32"
				repeated="true" desc="玩家的胜利次数"></param>
			<param fieldName="ulooseCount" tag="11" fieldType="int32"
				repeated="true" desc="玩家的失败次数"></param>
			<param fieldName="halo_id" tag="12" fieldType="int32" repeated="true"
				desc="光环"></param>
			<param fieldName="wings_id" tag="13" fieldType="int32"
				repeated="true" desc="翅膀"></param>
			<param fieldName="title_id" tag="14" fieldType="int32"
				repeated="true" desc="称号"></param>
		</toClient>
	</protocol>

	<protocol id="0x003C0D02" alias="requestMyPvpInfo">
		<toServer class="com.kueem.webgame.game.action.game.AsyncPvpAction"
			desc="请求同步个人PVP信息" method="myPvpInfo">
		</toServer>
	</protocol>


	<protocol id="0x003C0E02" alias="notifyTarget">
		<toClient desc="通知被挑战者的结果">
			<param fieldName="result" tag="1" fieldType="int32" desc="胜负"></param>
			<param fieldName="rank" tag="2" fieldType="int32" desc="排名"></param>
			<param fieldName="rankChange" tag="3" fieldType="int32"
				desc="排名变化情况 1上升 2下降 3不变"></param>
			<param fieldName="cid" tag="4" fieldType="string" desc="挑战者ID"></param>
			<param fieldName="name" tag="5" fieldType="string" desc="挑战者姓名"></param>
			<param fieldName="camp" tag="6" fieldType="int32" desc="挑战者阵营"></param>
			<param fieldName="vipLevel" tag="7" fieldType="int32" desc="挑战者VIP等级"></param>
			<param fieldName="vipTime" tag="8" fieldType="string" desc="挑战者VIP时间"></param>
		</toClient>
	</protocol>

</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/gem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="gem">
    <!--宝石系统 -->
    <protocol id="0x00130102" alias="hole">
        <toServer desc="装备打孔" class="com.kueem.webgame.game.action.game.GemAction" method="hole">
            <param fieldName="ueid" tag="1" fieldType="int32" />
            <param fieldName="is_bind_first" tag="2" fieldType="bool" />
            <param fieldName="auto_buy" tag="3" fieldType="bool" />
        </toServer>
    </protocol>
    <protocol id="0x00130202" alias="inlay">
        <toServer desc="宝石镶嵌" class="com.kueem.webgame.game.action.game.GemAction" method="inlay">
            <param fieldName="ueid" tag="1" fieldType="int32" />
            <param fieldName="poses" tag="2" fieldType="int32" repeated="true" />
            <param fieldName="indexList" tag="3" fieldType="int32" repeated="true" />
            <param fieldName="is_bind_first" tag="4" fieldType="bool" />
            <param fieldName="auto_buy" tag="5" fieldType="bool" />
        </toServer>
    </protocol>
    <protocol id="0x00130302" alias="remove">
        <toServer desc="宝石摘除" class="com.kueem.webgame.game.action.game.GemAction" method="remove">
            <param fieldName="ueid" tag="1" fieldType="int32" />
            <param fieldName="poses" tag="2" fieldType="int32" repeated="true" />
            <param fieldName="is_bind_first" tag="3" fieldType="bool" />
            <param fieldName="auto_buy" tag="4" fieldType="bool" />
        </toServer>
    </protocol>
    <protocol id="0x00130402" alias="synthesis">
        <toServer desc="宝石合成" class="com.kueem.webgame.game.action.game.GemAction" method="synthesis">
            <param fieldName="indexList" tag="1" fieldType="int32" repeated="true" />
            <param fieldName="numList" tag="2" fieldType="int32" repeated="true" />
            <param fieldName="useBaohufu" tag="3" fieldType="bool" />
            <param fieldName="is_bind_first" tag="4" fieldType="bool" />
            <param fieldName="auto_buy" tag="5" fieldType="bool" />
        </toServer>
    </protocol>
    <protocol id="0x00130602" alias="batch_synthesis">
        <toServer desc="批量宝石合成" class="com.kueem.webgame.game.action.game.GemAction" method="batch_synthesis">
            <param fieldName="gemId" tag="1" fieldType="int32" />
            <param fieldName="bound" tag="2" fieldType="int32" />
            <param fieldName="gemNum" tag="3" fieldType="int32" />
            <param fieldName="num" tag="4" fieldType="int32" />
            <param fieldName="useBaohufu" tag="5" fieldType="bool" />
            <param fieldName="flag" tag="6" fieldType="bool" />
            <param fieldName="is_bind_first" tag="7" fieldType="bool" />
            <param fieldName="auto_buy" tag="8" fieldType="bool" />
        </toServer>
    </protocol>
    <protocol id="0x00130702" alias="batch_synthesis_result">
        <toClient desc="批量合成结果">
            <param tag="1" fieldType="int32" fieldName="" />
            <param tag="2" fieldType="int32" fieldName="" />
            <param tag="3" fieldType="int32" fieldName="" />
        </toClient>
    </protocol>
    <protocol id="0x00130802" alias="refine">
        <toServer desc="宝石提纯" class="com.kueem.webgame.game.action.game.GemAction" method="refine">
            <param fieldName="type" tag="1" fieldType="int32" />
            <param fieldName="index" tag="2" fieldType="int32" />
            <param fieldName="pos" tag="3" fieldType="int32" />
            <param fieldName="num" tag="4" fieldType="int32" />
            <param fieldName="is_bind_first" tag="5" fieldType="bool" />
            <param fieldName="auto_buy" tag="6" fieldType="bool" />
        </toServer>
    </protocol>
    <protocol id="0x00130902" alias="transform_base">
        <toServer desc="基础宝石转换" class="com.kueem.webgame.game.action.game.GemAction" method="transform_base">
            <param fieldName="indexList" tag="1" fieldType="int32" repeated="true" />
            <param fieldName="numList" tag="2" fieldType="int32" repeated="true" />
            <param fieldName="attributeList" tag="3" fieldType="int32" repeated="true" />
        </toServer>
    </protocol>
    <protocol id="0x00130A02" alias="transform_special">
        <toServer desc="特性宝石转换" class="com.kueem.webgame.game.action.game.GemAction" method="transform_special">
            <param fieldName="indexList" tag="1" fieldType="int32" repeated="true" />
            <param fieldName="numList" tag="2" fieldType="int32" repeated="true" />
        </toServer>
    </protocol>
    <protocol id="0x00130B02" alias="synthesis_result">
        <toClient desc="合成结果">
            <param tag="1" fieldType="bool" fieldName="" />
        </toClient>
    </protocol>
</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/exp_pagoda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="exp_pagoda">
    <protocol id="0x00260102" alias="getExp">
        <toServer desc="领取经验 " class="com.kueem.webgame.game.action.game.ExpPagodaAction" method="getExp">
        </toServer>
    </protocol>
    <protocol id="0x00260202" alias="syncGetExp">
        <toClient desc="返回领取经验">
            <param fieldName="state" tag="1" fieldType="int32" />
        </toClient>
    </protocol>


    <protocol id="0x00260502" alias="levelUpTellFriends">
        <toServer desc="玩家升级后，需要向服务端推送一个向所有好友索要的一个祝福请求  " class="com.kueem.webgame.game.action.game.ExpPagodaAction" method="levelUpTellFriends">
        </toServer>
    </protocol>
    <protocol id="0x00260602" alias="requestBlessings">
        <toClient desc="收到玩家索要的祝福请求">
            <param fieldName="name" tag="1" fieldType="string" />
            <param fieldName="level" tag="2" fieldType="int32" />
            <param fieldName="gender" tag="3" fieldType="string" />
            <param fieldName="camp" tag="4" fieldType="int32" />
            <param fieldName="id" tag="5" fieldType="string" />
        </toClient>
    </protocol>



    <protocol id="0x00260702" alias="sendBlessing">
        <toServer desc="向服务端发送祝福好友  " class="com.kueem.webgame.game.action.game.ExpPagodaAction" method="sendBlessing">
            <param fieldName="friendId" tag="1" fieldType="string" />

        </toServer>
    </protocol>
    <protocol id="0x00260802" alias="syncSendBlessing">
        <toClient desc="返回　向服务端发送祝福好友 ">
            <param fieldName="state" tag="1" fieldType="int32" />
            <param fieldName="id" tag="2" fieldType="string" />
            <param fieldName="name" tag="3" fieldType="string" />
            <param fieldName="count" tag="4" fieldType="int32" />
            <param fieldName="exp" tag="5" fieldType="int32" />

        </toClient>
    </protocol>

    <protocol id="0x00260902" alias="receiveBlessing">
        <toClient desc="收到好友的祝福 ">
            <param fieldName="id" tag="1" fieldType="string" />
            <param fieldName="name" tag="2" fieldType="string" />
            <param fieldName="exp" tag="3" fieldType="int32" />
        </toClient>
    </protocol>


    <protocol id="0x00261002" alias="getExpPagoda">
        <!-- 供初始化用(比如：当前经验，当前一键次数,当前祝福好友数); -->
        <toServer desc="请求查询模块公共信息" class="com.kueem.webgame.game.action.game.ExpPagodaAction" method="getExpPagoda">
        </toServer>
    </protocol>
    <protocol id="0x00261102" alias="syncGetExpPagoda">
        <toClient desc="返回宝塔信息">
            <param fieldName="exp" tag="1" fieldType="int32" />
            <param fieldName="oneKeyTime" tag="2" fieldType="int32" />
            <param fieldName="sendBlessingTime" tag="3" fieldType="int32" />
        </toClient>
    </protocol>


</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/faction_battle.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="faction_battle">
	<protocol id="0x001C0102" alias="enterFor">
		<toServer desc="帮派战报名" class="com.kueem.webgame.game.action.game.FactionBattleAction" method="enterFor">
		</toServer>
	</protocol>
	<protocol id="0x001C0202" alias="goInto">
		<toServer desc="进入帮派战" class="com.kueem.webgame.game.action.game.FactionBattleAction" method="goInto">
		</toServer>
	</protocol>
	<protocol id="0x001C0302" alias="gainUserJoin">
		<toClient desc="返回报名列表">
			<param fieldName="user_id" tag="1" fieldType="string" repeated="true" />
			<param fieldName="user_name" tag="2" fieldType="string" repeated="true" />
			<param fieldName="force" tag="3" fieldType="int32" repeated="true" /><!--战斗力 -->
		</toClient>
		<toServer desc="获取报名列表" class="com.kueem.webgame.game.action.game.FactionBattleAction" method="gainUserJoin">
		</toServer>
	</protocol>
	<protocol id="0x001C0402" alias="gainGameArrange">
		<toClient desc="返回赛事安排">
			<param fieldName="faction_name_left" tag="1" fieldType="string" repeated="true" />
			<param fieldName="faction_name_right" tag="2" fieldType="string" repeated="true" />
			<param fieldName="enter_for_num" tag="3" fieldType="int32" /><!--报名帮派个数 -->
		</toClient>
		<toServer desc="获取赛事安排" class="com.kueem.webgame.game.action.game.FactionBattleAction" method="gainGameArrange">
		</toServer>
	</protocol>
	<protocol id="0x001C0502" alias="syncRankingsList">
		<toClient desc="返回本次帮战的个人排行(第一页)和帮派排行">
			<param fieldName="faction_rankings" tag="1" fieldType="int32" repeated="true" />
			<param fieldName="faction_name" tag="2" fieldType="string" repeated="true" />
			<param fieldName="join_num" tag="3" fieldType="int32" repeated="true" />
			<param fieldName="rankings_score" tag="4" fieldType="int32" repeated="true" />
			<param fieldName="battle_score" tag="5" fieldType="int32" repeated="true" />

			<param fieldName="personal_rankings" tag="6" fieldType="int32" repeated="true" />
			<param fieldName="user_name" tag="7" fieldType="string" repeated="true" />
			<param fieldName="faction_name" tag="8" fieldType="string" repeated="true" />
			<param fieldName="kill_num" tag="9" fieldType="int32" repeated="true" />
			<param fieldName="assist_num" tag="10" fieldType="int32" repeated="true" />
			<param fieldName="zhangong" tag="11" fieldType="int32" repeated="true" />
			<param fieldName="total_size" tag="12" fieldType="int32" repeated="false" /><!--总条数 -->
		</toClient>
	</protocol>
	<protocol id="0x001C0602" alias="syncMyReward">
		<toClient desc="返回本次帮战的玩家奖励">
			<param fieldName="person_xp" tag="1" fieldType="int32" repeated="false" />
			<param fieldName="person_contibution" tag="2" fieldType="int32" repeated="false" />
			<param fieldName="faction_resource" tag="3" fieldType="int32" repeated="false" />
		</toClient>
	</protocol>
	<protocol id="0x001C0702" alias="notifyRoundEnd">
		<toClient desc="通知客户端本轮比赛结束">
		</toClient>
	</protocol>
	<protocol id="0x001C0802" alias="gainBattleRecord">
		<toClient desc="返回最近一次帮派战绩和帮派排名">
			<param fieldName="person_contibution" tag="1" fieldType="int32" repeated="false" /><!--个人战功 -->
			<param fieldName="kill_num" tag="2" fieldType="int32" repeated="false" /><!--击杀次数 -->
			<param fieldName="personal_rankings" tag="3" fieldType="int32" repeated="false" /><!--个人排名 -->
			<param fieldName="assist_num" tag="4" fieldType="int32" repeated="false" /><!--助攻次数 -->
			<param fieldName="faction_rankings" tag="5" fieldType="int32" repeated="true" /><!--帮派排名 -->
			<param fieldName="faction_name" tag="6" fieldType="string" repeated="true" /><!--帮派名称 -->
			<param fieldName="faction_camp" tag="7" fieldType="int32" repeated="true" /><!--国家 -->
			<param fieldName="rankings_score" tag="8" fieldType="int32" repeated="true" /><!--帮派积分 -->
			<param fieldName="battle_score" tag="9" fieldType="int32" repeated="true" /><!--帮派战分 -->
		</toClient>
		<toServer desc="获取本次帮战的个人排行" class="com.kueem.webgame.game.action.game.FactionBattleAction" method="gainBattleRecord">
		</toServer>
	</protocol>
	<protocol id="0x001C0902" alias="gainPersonalRankings">
		<toClient desc="返回本次帮战指定页数的个人排行">
			<param fieldName="personal_rankings" tag="1" fieldType="int32" repeated="true" />
			<param fieldName="user_name" tag="2" fieldType="string" repeated="true" />
			<param fieldName="faction_name" tag="3" fieldType="string" repeated="true" />
			<param fieldName="kill_num" tag="4" fieldType="int32" repeated="true" />
			<param fieldName="assist_num" tag="5" fieldType="int32" repeated="true" />
			<param fieldName="zhangong" tag="6" fieldType="int32" repeated="true" />
		</toClient>
		<toServer desc="获取本次帮战指定页数的个人排行" class="com.kueem.webgame.game.action.game.FactionBattleAction" method="gainPersonalRankings">
			<param fieldName="page" tag="1" fieldType="int32" />
		</toServer>
	</protocol>
</config>

=== kitsudog/PacketDoctor/GameSniffer/src/main/resources/sniffer/jssg/message/item.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "//Message/" "message.dtd">
<config namespace="item">
    <protocol id="0x00080102" alias="use">
        <toServer desc="使用道具" class="com.kueem.webgame.game.action.game.ItemAction" method="use">
            <param fieldName="itemId" tag="1" fieldType="int32" />
            <param fieldName="number" tag="2" fieldType="int32" />
        </toServer>
    </protocol>
    <protocol id="0x00080202">
        <toServer class="com.kueem.webgame.game.action.game.ItemAction" desc="购买接口" method="buy">
            <param tag="1" fieldType="int32" fieldName="itemId" desc="道具id" />
            <param tag="2" fieldType="int32" fieldName="number" desc="数量" />
            <param tag="3" fieldType="int32" fieldName="option" desc="0 单纯的购买,1 保证数量(所有背包里的也算)" />
        </toServer>
        <returnMsg>
            <msg value="购买没有发生" id="1" />
            <msg value="购买失败" id="2" />
        </returnMsg>
    </protocol>
    <protocol id="0x00080302">
        <toServer class="com.kueem.webgame.game.action.game.ItemAction" desc="购买并使用" method="buyAndUse">
            <param tag="1" fieldType="int32" fieldName="itemId" desc="道具id" />
            <param tag="2" fieldType="int32" fieldName="number" desc="数量" />
            <param tag="3" fieldType="int32" fieldName="option" desc="0 严格执行,1 允许部分使用但购买足够,2 允许使用购买也不足够" />
        </toServer>
        <returnMsg>
            <msg value="不需要购买" id="1" />
            <msg value="购买失败了" id="2" />
            <msg value="使用失败了" id="3" />
        </returnMsg>
    </protocol>
</config>
